# Question 2

In [1]:
import cv2 as cv
import numpy as np
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import LeaveOneOut

## Create descriptors using SIFT

In [2]:
# sample_train = X_train[0]
img_dota = cv.imread("dota.jpg")
# cv.imshow("dota", img_dota)

In [3]:
img_dota.shape

(353, 616, 3)

In [4]:
type(img_dota)

numpy.ndarray

In [5]:
# Function to extract features using SIFT
def extract_sift_features(image):
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    sift = cv.ORB_create()
    kp, des = sift.detectAndCompute(gray, None)
    return gray, kp, des

In [6]:
meta = extract_sift_features(img_dota)
gray_img = meta[0]
keypoints = meta[1]
descriptor = meta[2]

In [7]:
print(descriptor)

[[ 73 120  63 ...  35  71 126]
 [164  98 233 ... 251  86 192]
 [238 106 226 ... 117 126 198]
 ...
 [ 41 181  24 ...  66 138  17]
 [173 248 180 ... 125  89 207]
 [210 189 188 ...  84 135  90]]


In [8]:
gray_img.shape

(353, 616)

In [9]:
kp_img = cv.drawKeypoints(gray_img, keypoints, img_dota, flags=cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv.imshow("keypoint", kp_img)

In [10]:
cv.waitKey(0)
cv.destroyAllWindows()